### ISSUE TITLE
Dynaaminen importtaus

### ISSUE THREAD

**Issue by funnicus** [EliteInsmatSoft/SihteeriBot#1]
Dynaaminen importtaus around **index.ts** riveillä 20-37 ei toimi, kun TypeScript compiletaan. Osaako joku keksiä tähän hyvän ratkaisun🤔 esim. @kumpmati ? En jaksa miettii ainakaa tänää enää😅
Tein ratkaisun tämän avulla: [https://discordjs.guide/command-handling/#dynamically-reading-command-files](url), joka tietenkin on JavaScriptiä, niin ei suoraan toimi... Liittyy varmaankin noihi polkuihin taas...

**Comment by funnicus** [comment]
Ehkä hyödyllinen: [https://stackoverflow.com/questions/61114027/node-js-and-typescript-how-to-dynamically-access-imported-modules](url)...

**Comment by kumpmati** [comment]
Toi taitaa johtuu siit et sillon ku suorittaa `npm start`-komennol ni se suorittaa sen koodin projektin juurikansiost. Se käännetty koodi yrittää importtaa niit komentoi kansiosta `./commands`, eli kansiost `<juuri>/commands` eikä `<juuri>/build/commands` ni siks epäonnistuu. Sit jos vaihtaa terminaalin kansioon `/build` ja suorittaa siel `node index.js` ni importtaa oikein.

**Comment by kumpmati** [comment]
Lisäks kans se yrittää importtaa `.ts`-tiedostoo vaik se compilettu koodi on `.js`.
Laitan jonku fixin kasaa

**Comment by kumpmati** [comment]
#2

**Comment by funnicus** [comment]
matias did fix
